/*
-- Query: SELECT * FROM nodeflix.peliculas
LIMIT 0, 1000

-- Date: 2024-07-03 18:09
*/
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (1,1,'Dracula','Drácula es una novela de fantasía gótica escrita por Bram Stoker, publicada en 1897.​​ Publicada en castellano por Ediciones Hymsa bajo la colección La novela aventura en 1938, con portada de Juan Pablo Bocquet e ilustraciones de Femenía','/images/ficcion/dracula.jpg','https://www.youtube.com/embed/WcDFYtF8pSc?si=rba7QbAglmsX1cmX','2014',92,'dracula','#dracula');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (2,1,'2012','Un escritor fracasado intenta llevar a su familia a un lugar seguro, mientras que el mundo se desintegra bajo el efecto de una serie de cataclismos.','/images/ficcion/2012.jpg','https://www.youtube.com/embed/AcZ-ffVxhpo?si=QMSRV2wkw_2BOIAt\"','2009',158,'2012','#2012');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (3,1,'Divergente','En una sociedad futurista, la gente está dividida entre facciones basadas en sus personalidades. Después de que una joven descubre que ella es una divergente y nunca será de ningún grupo, revela un complot para destruir a quienes son como ella.','/images/ficcion/Divergente.jpg','https://www.youtube.com/embed/_MHJPwThKNQ?si=9kk3SZKKvToG8TBo','2016',139,'divergente','#divergente');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (4,1,'Los juegos Del Hambre: La balada de los pajaros cantores','Años antes de convertirse en el tiránico presidente de Panem, Coriolanus Snow, de 18 años de edad, ve una oportunidad para un cambio de suerte cuando es mentor de Lucy Gray Baird, la tributo del Distrito 12.','/images/ficcion/HunterGames.jpg','https://www.youtube.com/embed/HgO58Q3I5J0?si=Wcwu21aeZpFAsudY','2023',157,'juegosDelHambre','#juegosDelHambre');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (5,1,'Planeta de los simios: Nuevo Reino','Muchos años después de la época de César, los simios se han dividido en clanes y los hombres se han vuelto salvajes. Un clan brutal secuestra a la tribu del chimpancé Noa, pero, con la ayuda de una humana, emprende la misión de rescatarlos.','/images/ficcion/planetaDeLosSimios.jpg','https://www.youtube.com/embed/OcBktw-5QlE?si=c40S15CuqHFGni0F','2024',115,'planetaDeLosSimios','#planetaDeLosSimios');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (6,1,'Guerra Mundial Z','Cuando una pandemia de zombis amenaza con destruir a la humanidad, un exinvestigador de Naciones Unidas es obligado a regresar al servicio para intentar descubrir la fuente de la infección.','/images/ficcion/guerraMundialZ.jpg','https://www.youtube.com/embed/M0T0EPJIg7A?si=h1K83jggwxwwKKvP','2013',116,'guerraMundialZ','#guerraMundialZ');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (7,2,'Anabelle','John Form encuentra el regalo perfecto para Mia, su esposa embarazada: una preciosa muñeca antigua llamada Annabelle. Una noche, una secta satánica les ataca brutalmente y provocan que un ente maligno se apodere de Annabelle.','/images/terror/Annabelle.jpg','https://www.youtube.com/embed/8kmLHwKH31M?si=bHbN1Upv1NSsnCnA','2014',95,'annabelle','#annabelle');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (8,2,'It','Varios niños de una pequeña ciudad del estado de Maine se alían para combatir a una entidad diabólica que adopta la forma de un payaso y desde hace mucho tiempo emerge cada 27 años para saciarse de sangre infantil.','/images/terror/it.jpg','https://www.youtube.com/embed/_oBZ_zTz0Nw?si=8waQULEs_tp_SvC5','2017',135,'it','#it');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (9,2,'La Monja','Una monja se suicida en una abadía rumana y el Vaticano envía a un sacerdote y una novicia a investigar lo sucedido. Lo que ambos encuentran allá es un secreto perverso que los enfrentará cara a cara con el mal en su esencia más pura.','/images/terror/laMonja.jpg','https://www.youtube.com/embed/AKpPeLAMY9I?si=YpdgWlkcTVnVMCja','2018',96,'laMonja','#laMonja');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (10,2,'Un lugar en Silencio','En el año 2020, unas criaturas misteriosas con un sentido auditivo extraordinario han diezmado a la población mundial. Una familia se oculta en una cabaña y se comunica mediante la lengua de signos para no ser cazados por estos monstruos.','/images/terror/unLugarEnSilencio.jpg','https://www.youtube.com/embed/VWRNNpoar-E?si=Cbj_mzLvqaK8uoYj','2018',90,'unLugarEnSilencio','#unLugarEnSilencio');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (11,2,'Scream','Sam, Tara, Chad y Mindy, los cuatro supervivientes de la matanza de Woodsboro, abandonan el pueblo para empezar de cero en Nueva York. Sin embargo, Ghostface los persigue hasta la gran ciudad para terminar con todos ellos.','/images/terror/Scream.jpg','https://www.youtube.com/embed/03n1lgk8E9U?si=9VYdoe__kRBreVrG','2023',122,'scream','#scream');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (12,2,'Smile','Tras presencia el dramático incidente sufrido por un paciente, la Dra. Cotter empieza a experimentar hechos aterradores sin explicación aparente. A medida que el horror se adueña de su vida, comprende que la respuesta está en su propio pasado.','/images/terror/Smile.jpg','https://www.youtube.com/embed/yhKiQGJop_8?si=0yCZxHfqC3PJkba1','2022',115,'smile','#smile');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (13,3,'Joker','Arthur Fleck adora hacer reír a la gente, pero su carrera como comediante es un fracaso. El repudio social, la marginación y una serie de trágicos acontecimientos lo conducen por el sendero de la locura y, finalmente, cae en el mundo del crimen.','/images/accion/joker.jpg','https://www.youtube.com/embed/TobNCFMK_bs?si=cBFVU3pFprtcu70B','2019',122,'joker','#joker');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (14,3,'Indestructibles','Barney, Christmas y el resto del equipo deben enfrentarse a Conrad Stonebanks, cofundador del grupo que se convirtió en un despiadado traficante de armas. Barney estaba convencido de haber acabado con él, pero ha vuelto y ahora busca venganza.','/images/accion/indestructibles.jpg','https://www.youtube.com/embed/O6W1Q04bHjA?si=OxeYUszjpy2Y9oma','2014',126,'indestructibles','#indestructibles');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (15,3,'Mad Max','Aunque está decidido a vagar solo por el páramo post-apocalíptico, Mad Max se une a Furiosa, una comandante fugitiva, y su banda, quienes están tratando de escapar de un señor de la guerra.','/images/accion/madMax.jpg','https://www.youtube.com/embed/1bsnGZq2zDU?si=_XczEp1kPuEyLWEY','2015',114,'madMax','#madMax');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (16,3,'Rapidos y furiosos X','Dom Toretto y sus familias se enfrentan al peor enemigo imaginable, uno llegado desde el pasado con sed de venganza, dispuesto a cualquier cosa con tal de destruir todo aquello que Dom ama.','/images/accion/rapidosYFuriosos.jpg','https://www.youtube.com/embed/FDhvbIqTQwI?si=xVxcWr_1kbm3pmEs','2023',140,'rapidosYFuriosos','#rapidosYFuriosos');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (17,3,'El Justiciero','Robert McCall, un antiguo comando de operaciones especiales que ha fingido su propia muerte, se ve obligado a salir de su retiro para salvar la vida de Teri, una joven que se encuentra en manos de unos mafiosos rusos ultraviolentos.','/images/accion/equalizer.jpg','https://www.youtube.com/embed/rlMaxFG7blg?si=8g8HUGyTfVJZ-tfY','2014',132,'elJusticiero','#elJusticiero');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (18,3,'Matrix Resurrection ','Acosado por extraños recuerdos, la vida de Neo toma un giro inesperado al encontrarse, nuevamente, dentro de la Matrix.','/images/accion/matrix.jpg','https://www.youtube.com/embed/qjnvX44LoQw?si=iMVm3IIvKkdVor8V','2021',148,'matrix','#matrix');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (19,4,'After','Al ingresar al primer semestre de la universidad, el mundo de Tessa Young se abre y conoce a Hardin Scott, un rebelde misterioso que la hace cuestionarse todo lo que sabe sobre su persona y lo que desea para su vida.','/images/romance/After.jpg','https://www.youtube.com/embed/n1tsEQ7-U7o?si=I4w_aAAaRPFWdSl0','2019',106,'after','#after');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (20,4,'Yo antes de ti','La vida de Louisa Clark, una chica alegre y alocada, que va empalmando un trabajo con otro para ayudar a su familia a subsistir, cambia por completo cuando comienza a trabajar como cuidadora de un joven millonario, quien quedó paralítico tras un accidente. Poco a poco, se va estableciendo entre ellos una conexión cada vez más íntima','/images/romance/Antesdeti.jpg','https://www.youtube.com/embed/FRrc2X4Uzm4?si=O_D7JWSS7UYDRvrk','2016',110,'antesDeTi','#antesDeTi');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (21,4,'Cuestion de Tiempo','Cuando Tim Lake cumple 21 años, su padre le dice un secreto: los hombres de su familia pueden viajar por el tiempo. A pesar de que él no puede cambiar la historia, Tim decide mejorar su vida buscando una novia. Él conoce a Mary, se enamora y finalmente se gana su corazón con los viajes en el tiempo ','/images/romance/CuestionDeTiempo.jpg','https://www.youtube.com/embed/5DQAZtFHLEA?si=4Z1oxfQB5iQBT6FM','2013',123,'cuestionDeTiempo','#cuestionDeTiempo');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (22,4,'Si decido quedarme','Cuando un accidente automovilístico la deja entre la vida y la muerte, una adolescente debe enfrentar una decisión que determinará su destino final.','/images/romance/SiDecidoQuedarme.jpg','https://www.youtube.com/embed/B0chmofGqpk?si=cMgS3tPRNfL_ZUCD\"','2014',107,'siDecidoQuedarme','#siDecidoQuedarme');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (23,4,'Stand de los besos','El primer beso de Elle marca el inicio de un romance prohibido con el chico más lindo de la escuela, pero también podría ser el fin de su relación con su mejor amigo.','/images/romance/StandDeLosBesos.jpg','https://www.youtube.com/embed/L5nYYBxg52A?si=8i-9JXrgOGGCeS9e','2018',105,'standDeLosBesos','#standDeLosBesos');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (24,4,'Crepusculo','Bella Swan se va a vivir con su padre al pequeño pueblo de Forks, donde conoce a Edward, un atractivo y misterioso chico del que se enamora y quien esconde un gran secreto: es un vampiro. Pero la familia del chico guarda una peculiaridad, y es que no se alimenta de sangre humana.','/images/romance/crepusculo.jpg','https://www.youtube.com/embed/6UTwp0Qv_Sg?si=31B51j3bxDoIWLW','2008',122,'crepusculo','#crepusculo');
