/*
-- Query: SELECT * FROM nodeflix.peliculas_recomendadas
LIMIT 0, 1000

-- Date: 2024-07-03 18:10
*/
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (1,1,'Los juegos Del Hambre: La balada de los pajaros cantores','Años antes de convertirse en el tiránico presidente de Panem, Coriolanus Snow, de 18 años de edad, ve una oportunidad para un cambio de suerte cuando es mentor de Lucy Gray Baird, la tributo del Distrito 12.','/images/ficcion/HunterGames.jpg','https://www.youtube.com/embed/HgO58Q3I5J0?si=Wcwu21aeZpFAsudY','2023',157,'juegosDelHambre','#juegosDelHambre');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (2,1,'Dracula','Drácula es una novela de fantasía gótica escrita por Bram Stoker, publicada en 1897.​​ Publicada en castellano por Ediciones Hymsa bajo la colección La novela aventura en 1938, con portada de Juan Pablo Bocquet e ilustraciones de Femenía','/images/ficcion/dracula.jpg','https://www.youtube.com/embed/WcDFYtF8pSc?si=rba7QbAglmsX1cmX','2014',92,'dracula','#dracula');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (3,2,'It','Varios niños de una pequeña ciudad del estado de Maine se alían para combatir a una entidad diabólica que adopta la forma de un payaso y desde hace mucho tiempo emerge cada 27 años para saciarse de sangre infantil.','/images/terror/it.jpg','https://www.youtube.com/embed/_oBZ_zTz0Nw?si=8waQULEs_tp_SvC5','2017',135,'it','#it');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (4,1,'Matrix Resurrection ','Acosado por extraños recuerdos, la vida de Neo toma un giro inesperado al encontrarse, nuevamente, dentro de la Matrix.','/images/accion/matrix.jpg','https://www.youtube.com/embed/qjnvX44LoQw?si=iMVm3IIvKkdVor8V','2021',148,'matrix','#matrix');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (5,2,'Un lugar en Silencio','En el año 2020, unas criaturas misteriosas con un sentido auditivo extraordinario han diezmado a la población mundial. Una familia se oculta en una cabaña y se comunica mediante la lengua de signos para no ser cazados por estos monstruos.','/images/terror/unLugarEnSilencio.jpg','https://www.youtube.com/embed/VWRNNpoar-E?si=Cbj_mzLvqaK8uoYj','2018',90,'unLugarEnSilencio','#unLugarEnSilencio');
INSERT INTO `` (`id`,`genero_id`,`titulo`,`descripcion`,`imagen`,`trailer`,`anio`,`duracion_minutos`,`modal`,`idmodal`) VALUES (6,3,'Rapidos y furiosos X','Dom Toretto y sus familias se enfrentan al peor enemigo imaginable, uno llegado desde el pasado con sed de venganza, dispuesto a cualquier cosa con tal de destruir todo aquello que Dom ama.','/images/accion/rapidosYFuriosos.jpg','https://www.youtube.com/embed/FDhvbIqTQwI?si=xVxcWr_1kbm3pmEs','2023',140,'rapidosYFuriosos','#rapidosYFuriosos');
